version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
  backend:
    build: .
    environment:
      - MONGO_HOST=mongo
    ports:
      - 8080:8080
    depends_on:
      - mongo